permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
baseurl: ""
url: "https://globalnames.org"
repository: https://github.com/GlobalNamesArchitecture/GlobalNamesArchitecture.github.io
highlighter: rouge

collections:
  docs:
    output: true
  apps:
    output: true
  workshops:
    output: true

markdown: kramdown
# kramdown:
#   hard_wrap: false
#   input: GFM

plugins:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll/scholar

scholar:
  style: ./_assets/bibliography/gn.csl
  locale: en

  sort_by: year,month
  order: descending

  group_by: year
  group_order: descending

  source: ./_assets/bibliography
  bibliography: refs.bib
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@* "
