markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/GlobalNamesArchitecture/GlobalNamesArchitecture.github.io

collections:
  docs:
    output: true
