source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'jekyll-coffeescript', '~> 2.0'
gem 'jekyll-gist', '~> 1.5'
gem 'jekyll-mentions', '~> 1.6'
gem 'jekyll-paginate', '~> 1.1'
gem 'jekyll-redirect-from', '~> 0.16'
gem 'jekyll-scholar', '~> 7.1'
gem 'jekyll-sitemap', '~> 1.4'
gem 'jemoji', '~> 0.13'
gem 'kramdown', '~> 2.4'
gem 'mime-types', '~> 3.4'
gem 'pygments.rb', '~> 2.4'
gem 'rake', '~> 13.0'
gem 'rouge', '~> 4.1'
gem 'solargraph', '~> 0.49'
gem 'webrick', '~> 1.8'
