source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-coffeescript'
gem 'jekyll-gist'
gem 'jekyll-mentions'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-scholar'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'kramdown'
gem 'mime-types'
gem 'pygments.rb'
gem 'rake'
gem 'rouge'
gem 'ruby-lsp'
