source 'https://rubygems.org'

gem 'jekyll', '~> 4.2'
gem 'jekyll-coffeescript', '~> 2.0'
gem 'jekyll-gist', '~> 1.5'
gem 'jekyll-mentions', '~> 1.6'
gem 'jekyll-paginate', '~> 1.1'
gem 'jekyll-redirect-from', '~> 0.16'
gem 'jekyll-scholar', '~> 6.8'
gem 'jekyll-sitemap', '~> 1.4'
gem 'jemoji', '~> 0.12'
gem 'kramdown', '~> 2.3'
gem 'mime-types', '~> 3.3'
gem 'pygments.rb', '~> 2.2'
gem 'rake', '~> 13.0'
gem 'rouge', '~> 3.26'
gem 'solargraph', '~> 0.40'
gem 'webrick', '~> 1.7'
