name: Bug Report
description: Bug/Feature for https://globalnames.org site.
labels: [bug]
body:
  - type: input
    attributes:
      label: Issue Title
      description: Describe your thoughts/reports here.

